### ISSUE TITLE
懒b悠要修复的emby的bug

### ISSUE THREAD

**Issue by RickyYYY0203** [juex123/embyIssue#1]
新妹魔王的契约者 第一季第七集字幕有问题 第二季缺集 11 12
![IMG_4067](https://github.com/user-attachments/assets/9975d6e8-536c-45a6-8924-4f5fbb4a5729)
![IMG_4068](https://github.com/user-attachments/assets/6b1f6ad3-9d4a-49bf-847b-afaeb07b3ab4)

**Comment by juex123** [comment]
换源并且增加了SP
